### ISSUE TITLE
Hey you guys might want to move this to a closed/private account, OhSK's Mapbox credentials are exposed on here.

### ISSUE THREAD

**Issue by kuanb** [urbanlaunchpad/SoloCityMap#52]
![screen shot 2015-01-13 at 4 56 11 pm](https://cloud.githubusercontent.com/assets/6053396/5732352/4234ab80-9b45-11e4-8413-330ca5a9189b.png)

**Comment by buzoherbert** [comment]
Hey
That one needs to be úblic anyway, since the user downloads the html stuff. But I think you can limit the calls to specific domains from the Mapbox account. At least that's what Google Maps does.

**Comment by kuanb** [comment]
ah good point
